---
- hosts: all

  vars:
    homeDir: /home/fikri
    appDir: "app/blog/{{ ansible_date_time.epoch }}/"
    releaseAppDir: app/blog/release

  tasks:
    - name: Clone app repository
      git:
        repo: git@github.com:firefin0/blog.git
        dest: "{{ homeDir }}/{{ appDir }}"

    - name: Install node modules
      command: npm install
      args:
        chdir: "{{ homeDir }}/{{ appDir }}"

    - name: Build app assets
      command: npm run build
      args:
        chdir: "{{ homeDir }}/{{ appDir }}"

    - name: Update dir symlink
      file:
        src: "{{ homeDir }}/{{ appDir }}"
        dest: "{{ homeDir }}/{{ releaseAppDir }}"
        state: link

    - name: Delete old pm2 process
      command: pm2 delete blog
      ignore_errors: yes
    
    - name: Start new pm2 process
      command: pm2 start "npm start" -n blog
